### ISSUE TITLE
Sprache der Webseite wählen

### ISSUE THREAD

**Issue by CoronaCircle** [CoronaCircles/coronacircles#13]
Es sollte ein Feld geben um die Sprache der Webseite zu wählen (en/de).
Idealer Weise werden die Emails auch in entsprechender Sprache versandt.

**Comment by ArneBo** [comment]
At the Moment the language will be automatically chosen by the default language of the clients browser. works pretty much. I would not use a german browser if I would not speak german. emails will automatically be sent in that language.
standard language if not german is english.
can we close this or do you insist on a language chooser? If yes where should it be? looks ugly in the menu now.

**Comment by CoronaCircle** [comment]
WOW. Ich dachte Rechts von CONTACT wäre ein kleines Feld um die Sprache zu ändern. Ist kein must-have aber mir ist es lieber selber bestimmen zu können.

**Comment by derhedwig** [comment]
> looks ugly in the menu now.
Ups, I overlooked that. Feel free to revert my changes.
