### ISSUE TITLE
E-Mail-Vorlage für Teilnehmen-E-Mail erstellen

### ISSUE THREAD

**Issue by derhedwig** [CoronaCircles/coronacircles#14]
Wenn man will, dass tatsächlich E-Mail verschickt werden, müssen auch Vorlagen im Backend erstellt werden. Am besten für alle Auswahlmöglichkeiten des Felds Typ.
Das sind zur Zeit 4 Stück:

 * Join Confirmation: Als Bestätigung, wenn man beitritt. Kann auch URL zum Austreten enthalten.
 * Host Confirmation: Als Bestätigung, wenn man hostet. Kann auch URL zum Löschen enthalten.
 * Join: Das sollte die Mail mit dem Jitsi-Link sein
 * Circle deleted Notification: Wenn der Host den Circle löscht, wird das an alle TN verschickt.

**Comment by CoronaCircle** [comment]
Hier sind unsere Email Templates (En): https://drive.google.com/file/d/1l872WFql9DyENUtYvfEbAwRYWQIzEt-g/view?usp=sharing
Ich bin dafür, schon in der Bestätigungsmail den Jitsi Link einzubetten. Die Erinnerungsemail schreibe ich jetzt noch in das Dokumente. Die Übersetzungen gibt es auch schon, können wir das über das CMS dann einfügen?

**Comment by derhedwig** [comment]
Schon in der Bestätigungsmail den Jitsi Link einfügen: Technisch geht das. Aber komischerweise dachte ich bis jetzt, dass es euer Konzept ist, dass der Link erst raus geht, wenn das Ding anfängt und dadurch niemand den Link zu früh hat.

Die "Erinnerungsmail" wird zur Zeit 5-10 Minuten vor Beginn verschickt. Eben weil ich bis jetzt dachte das es euer Konzept sei.

**Comment by CoronaCircle** [comment]
Ich weiß nicht woher diese Annahmen kommen. Ich dachte bislang nur an eine Mail nach dem Anmelden. Eine Erinnerungsmail finde ich nicht schlecht, aber 5-10 Minuten vor Beginn scheint mir zu kurz wenn Menschen es tatsächlich vergessen haben. Ich füge gerade die Templates ein.

**Comment by derhedwig** [comment]
okay, wann soll die Erinnerungsmail verschickt werden?

**Comment by GerrietSchwen** [comment]
Mein Vorschlag wäre eine Stunde vor Beginn.

**Comment by derhedwig** [comment]
Okay, habe ich im Quellcode geändert. Aber dass das auf der Seite ankommt ist Arnes Job, das kann ich gar nicht.
