### ISSUE TITLE
Hosting auf 

### ISSUE THREAD

**Issue by derhedwig** [CoronaCircles/coronacircles#15]
Das Hosting von https://coronacircles.herokuapp.com/ ist z.Z. nur zum Testen eingerichtet:
 * Es ist wahrscheinlich nicht die richtige Domain?
 * Der Server fährt nach 30 Minuten runter.
 * E-Mail können nur an verifizierte E-Mail-Adressen verschickt werden.
 * Es können keine Bilder hochgeladen werden

Soll es bei heroku gehostet werden?
Kosten sind etwa 7$ / Monat.
Dann muss ein bezahltes Konto bei heroku erstellt werden. Das kann auch ich machen.
Dann kann man auch ein Konto bei AWS machen, um dort die Bilder zu speichern.
Wenn es eine Domain gibt, kann man die mit der Seite verknüpfen.
Und mit der Domain kann man dann auch das Versenden an beliebige E-Mail-Adressen aktivieren.

**Comment by ArneBo** [comment]
Alternativ bei ecobytes.net
Ich bin da Mitglied und kann das über mich laufen lassen und dann separat in Rechnung stellen. Kostenpunkt: Spende.
Dort läuft auch der jitsi server.
Bräuchte Hilfe beim Einrichten @derhedwig. Hast Du Morgen Zeit?

**Comment by derhedwig** [comment]
Also: Es wird offenbar auf ecobytes.net gehostet.
