### ISSUE TITLE
Einfache Unterseiten reparieren

### ISSUE THREAD

**Issue by derhedwig** [CoronaCircles/coronacircles#18]
Einfache Unterseiten funktionieren derzeit nicht, weil das ursprüngliche Site-Objekt gelöscht wurde.

Statt das zu debuggen könnte man diese sehr einfach Funktion (dass es Unterseiten gibt, die man im Backend bearbeiten kann) auch selber schreiben. Dann hat man keine Probleme mehr mit diesem Site-Objekt.

**Comment by ArneBo** [comment]
Also bei mir geht das trotz intakter Site ID nicht. Auch die Auflistung der Seiten im Footermenu.

**Comment by ArneBo** [comment]
Auf production geht es jetzt auch nicht, er verlinkt auf die site id url mit example.com vom admin, und die flatpages urls greifen auch nicht und im menü taucht es auch nicht auf.
Wie besprochen geht vielleicht ein eigenes Model kürzer als zu debuggen?
Dann gerne auch zweisprachig.
