### ISSUE TITLE
Alte Circles automatisch wieder löschen?

### ISSUE THREAD

**Issue by derhedwig** [CoronaCircles/coronacircles#21]
Sollen alte Circles nach Ablauf wieder gelöscht werden? Sagen wir so einen Tag nach stattfinden?

**Comment by CoronaCircle** [comment]
ich sehe keinen Grund die Circle weiter im Kalender anzuzeigen, nach dem sie angefangen haben. Daher könnten sie auch direkt mit dem Beginn gelöscht werden
