### ISSUE TITLE
Von Teilnahme an CoronaCircle wieder abmelden

### ISSUE THREAD

**Issue by CoronaCircle** [CoronaCircles/coronacircles#24]
Gibt's dafür schon einen  {{ event.abmelden }} oder ähnliches? Dann füge ich das ins Email Template für die Teilnahme ein.

**Comment by derhedwig** [comment]
duplicate of #8 

Ich habe das {{ leave_url }} genannt. Sollte auch in der Beschreibung des Textfelds der E-Mail-Vorlagen stehen.
Aber ich weiß nicht ob das auch auf coronacircles.net zur Verfügung steht.

**Comment by derhedwig** [comment]
Duplicate of #8
