### ISSUE TITLE
Mails versenden

### ISSUE THREAD

**Issue by CoronaCircle** [CoronaCircles/coronacircles#25]
Nach der Anmeldung muss das entsprechende Mailtemplate auch versand werden.

**Comment by derhedwig** [comment]
Damit E-Mails verschickt werden, müssen da einige Dinge zusammenkommen:
 * Die E-Mail-Vorlagen müssen erstellt sein unter /admin
 * Der Cronjob muss laufen, der regelmäßig guckt, ob Circles anfangen.
 * Es muss ein E-Mail-Anbieter per Umgebungsvariable eingestellt sein.

**Comment by CoronaCircle** [comment]
Die Mailtemplates habe ich unter /admin erstellt. Wenn es da noch was zu tun gibt, gebt mir gerne bescheid. Ansonsten kann der Issue gelöscht werden

**Comment by derhedwig** [comment]
Ich würde die erstmal Korrekturlesen, habe aber keinen Zugang.

**Comment by derhedwig** [comment]
Ich habe mir die E-Mail-Vorlagen angeguckt.
Es gab dort keine Syntaxfehler (daran liegt es also nicht).

Ein paar logische Fehler gab es, die ich korrigiert habe:
 * Die Variable {{ name }} gibt es nicht. Wir wissen ja gar nicht, wie die Leute heißen.
 * {{ event }} ist nicht die URL um sich als TN einzutragen. Ich habe dafür die neue Variable {{ event.participate_url }} erstellt.

Da es jetzt neuerdings verschiedene Zeitzonen gibt, habe ich im E-Mail-Text in Klammern die Zeitzone in Kurzschreibweise dazu geschrieben.

Ich habe dann die Templates auf die andere Seite unter https://coronacircles.herokuapp.com/ kopiert. Und es da ausprobiert. Da funktioniert alles. Alle drei eingetragenen E-Mail-Typen werden verschickt und die angegebenen Links funktionieren.

Es gibt allerdings einige Rechtschreib- und Grammatikfehler in den E-Mail-Vorlagen. Die Anrede wechselt auch zwischen Du und Sie hin und her. (Das habe ich nicht korrigiert)

**Comment by derhedwig** [comment]
Ich vermute also, dass auf https://coronacircles.net/ kein E-Mail-Anbieter eingetragen ist.

**Comment by CoronaCircle** [comment]
Danke Dir Hedwig,

bezüglich Grammatik und konsequentem Duzen liest einer von uns die Mails nochmals durch. Deine Anfrage zu Emailanbietern kann ich Dir leider nicht beantworten.

Gerriet
