### ISSUE TITLE
Geschäftsbedingungen 

### ISSUE THREAD

**Issue by CoronaCircle** [CoronaCircles/coronacircles#26]
Wenn ich mich auf der deutschen Seite zu einem Circle anmelde, werden statt "Teilnahmebedingungen" "Geschäftsbedingungen" angezeigt, außerdem der englische Text. Ich habe schon 2x versucht das zu ändern, war aber nicht erfolgreich.

**Comment by derhedwig** [comment]
Dieser Text (das nervige Popup) ist fest einprogrammiert. Auch die fest einprogrammierten Sachen haben Übersetzungen, aber ich hatte bis jetzt keine Lust diesen langen Text zu übersetzen.

Die Überschrift "Terms & Conditions" dagegen habe ich halt mit "Geschäftsbedingungen" übersetzt.

**Comment by derhedwig** [comment]
Also was soll hier dann passieren?
Soll einfach der Text übersetzt werden (technisch das einfachste)?
Oder soll das so programmiert sein, dass man den Text im Backend ändern kann?

**Comment by CoronaCircle** [comment]
Die Übersetzung https://docs.google.com/document/d/1YqdJx5QD-YPmi9Xy5aIdL17YrAI5cVQ-yzrQEcKzhD0/edit?usp=sharing) einfügen würde mir gerade reichen.

**Comment by derhedwig** [comment]
Ah, das kannte ich noch nicht.
