### ISSUE TITLE
You must never enable debug in production.

### ISSUE THREAD

**Issue by derhedwig** [CoronaCircles/coronacircles#34]
Mir ist aufgefallen, dass auf der Seite https://coronacircles.net/ offenbar DEBUG=True eingestellt ist. Das ist ein Sicherheitsproblem.

> You’re certainly developing your project with DEBUG = True, since this enables handy features like full tracebacks in your browser.
> For a production environment, though, this is a really bad idea, because it leaks lots of information about your project: excerpts of your source code, local variables, settings, libraries used, etc.

(https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/)

**Comment by ArneBo** [comment]
Oh, I left it on after the email debugging session. It was late.. Thanks for the reminder!
Should be fixed now.
